version: '3.1'

volumes:
  example_src:
services:
  
  example:
    image: typescript-boilerplate
    build:
      context: .
      dockerfile: Dockerfile
    user: "node"
    # env_file: 
    #   - back.env
    entrypoint: ["sh", "-c"]
    command: ["yarn prod"]
    volumes:
      - ./src:/home/node/app/src

    ports:
      - 3000:3000
    networks:
      - example

networks:
  example: